"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.client = exports.db = void 0;
var postgres_js_1 = require("drizzle-orm/postgres-js");
var postgres_1 = require("postgres");
require("dotenv/config");
var dbName = process.env.DB_NAME;
var dbUser = process.env.DB_USER;
var dbPassword = process.env.DB_PASSWORD;
var dbHost = process.env.DB_HOST;
var dbUrl = "postgres://".concat(dbUser, ":").concat(dbPassword, "@").concat(dbHost, "/").concat(dbName);
exports.db = (0, postgres_js_1.drizzle)((0, postgres_1.default)(dbUrl));
exports.client = (0, postgres_1.default)(dbUrl);
