name: Alexandri Backend CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  backend:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: alexandri
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    env:
      DATABASE_URL: postgresql://postgres:postgres@localhost:5432/alexandri
      NODE_ENV: test

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install
        working-directory: Backend

      - name: Inject .env from GitHub secret
        run: echo "${{ secrets.ENV_FILE }}" > .env
        working-directory: Backend

      - name: Wait for PostgreSQL
        run: |
          until pg_isready -h localhost -p 5432; do
            echo "⏳ Waiting for PostgreSQL..."
            sleep 2
          done

      - name: Run DB migrations
        run: npx drizzle-kit push
        working-directory: Backend

      - name: Run tests
        run: npm run test
        working-directory: Backend
