name: Deploy to AWS EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Add EC2 to known hosts
        run: |
          ssh-keyscan -H ec2-13-53-198-252.eu-north-1.compute.amazonaws.com >> ~/.ssh/known_hosts

      - name: Deploy via SSH
        run: |
          ssh ec2-user@ec2-13-53-198-252.eu-north-1.compute.amazonaws.com << 'EOF'
            cd /home/ec2-user/Alexandrie_library
            git pull origin main
            docker-compose down
            docker-compose build --no-cache
            docker-compose up -d
          EOF
